Post http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"lin",
    "password":"lin"
}
###
GET http://localhost:3001/api/users
###
DELETE http://localhost:3001/api/users/62cf31d999b7b5282318c536