GET http://localhost:3001/api/blogs/62e02f68ef579bdff193f10f/comments
###
POST http://localhost:3001/api/blogs/62e02f68ef579bdff193f10f/comments
Content-Type: application/json

{
    "comment": "first"
}